global:
  scrape_interval: 20s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: "Proxy LAX"
    static_configs:
      # Replace this with the IP address or hostname of your server
      # This will be the service name for Docker Compose users
      - targets: [ "72.5.46.63:25627" ]
        # Customize or/and rewrite your labels (optional)
        labels:
          # The instance label will be shown on the dashboard
          # This is the server's IP address by default
          instance: "lax-proxy.trilogymc.net"
          friendly_name: "Proxy LAX"
          environment: "production"


  - job_name: "Skyblock LAX"
    static_configs:
      # Replace this with the IP address or hostname of your server
      # This will be the service name for Docker Compose users
      - targets: [ "72.5.46.63:25571" ]
        # Customize or/and rewrite your labels (optional)
        labels:
          # The instance label will be shown on the dashboard
          # This is the server's IP address by default
          instance: "lax-skyblock.trilogymc.net"
          friendly_name: "Skyblock LAX"
          environment: "production"

  - job_name: "Hardcore LAX"
    static_configs:
      # Replace this with the IP address or hostname of your server
      # This will be the service name for Docker Compose users
      - targets: [ "72.5.46.63:25639" ]
        # Customize or/and rewrite your labels (optional)
        labels:
          # The instance label will be shown on the dashboard
          # This is the server's IP address by default
          instance: "lax-hardcore.trilogymc.net"
          friendly_name: "Hardcore LAX"
          environment: "production"


  - job_name: "Development LAX"
    static_configs:
      # Replace this with the IP address or hostname of your server
      # This will be the service name for Docker Compose users
      - targets: [ "72.5.46.63:25651" ]
        # Customize or/and rewrite your labels (optional)
        labels:
          # The instance label will be shown on the dashboard
          # This is the server's IP address by default
          instance: "dev-lax.trilogymc.net"
          friendly_name: "Dev LAX"
          environment: "dev"


  - job_name: "Normal Survival ASH"
    static_configs:
      # Replace this with the IP address or hostname of your server
      # This will be the service name for Docker Compose users
      - targets: [ "45.59.171.173:25639" ]
        # Customize or/and rewrite your labels (optional)
        labels:
          # The instance label will be shown on the dashboard
          # This is the server's IP address by default
          instance: "normalsurvival-ash.trilogymc.net"
          friendly_name: "Normal Survival ASH"
          environment: "production"


  - job_name: "Skyblock ASH"
    static_configs:
      # Replace this with the IP address or hostname of your server
      # This will be the service name for Docker Compose users
      - targets: [ "45.59.171.173:25651" ]
        # Customize or/and rewrite your labels (optional)
        labels:
          # The instance label will be shown on the dashboard
          # This is the server's IP address by default
          instance: "skyblock-ash.trilogymc.net"
          friendly_name: "Skyblock ASH"
          environment: "production"


  - job_name: "Proxy ASH"
    static_configs:
      # Replace this with the IP address or hostname of your server
      # This will be the service name for Docker Compose users
      - targets: [ "45.59.171.173:25593" ]
        # Customize or/and rewrite your labels (optional)
        labels:
          # The instance label will be shown on the dashboard
          # This is the server's IP address by default
          instance: "proxy-ash.trilogymc.net"
          friendly_name: "Proxy ASH"
          environment: "production"


  - job_name: "Lobby LAX"
    static_configs:
      # Replace this with the IP address or hostname of your server
      # This will be the service name for Docker Compose users
      - targets: [ "72.5.46.63:25569" ]
        # Customize or/and rewrite your labels (optional)
        labels:
          # The instance label will be shown on the dashboard
          # This is the server's IP address by default
          instance: "proxy-lax.trilogymc.net"
          friendly_name: "Proxy LAX"
          environment: "production"


  - job_name: "Lobby ASH"
    static_configs:
      # Replace this with the IP address or hostname of your server
      # This will be the service name for Docker Compose users
      - targets: [ "45.59.171.173:25602" ]
        # Customize or/and rewrite your labels (optional)
        labels:
          # The instance label will be shown on the dashboard
          # This is the server's IP address by default
          instance: "lobby-ash.trilogymc.net"
          friendly_name: "Lobby ASH"
          environment: "production"

  - job_name: "Creative LAX"
    static_configs:
      # Replace this with the IP address or hostname of your server
      # This will be the service name for Docker Compose users
      - targets: [ "72.5.46.63:25566" ]
        # Customize or/and rewrite your labels (optional)
        labels:
          # The instance label will be shown on the dashboard
          # This is the server's IP address by default
          instance: "creative-lax.trilogymc.net"
          friendly_name: "Creative LAX"
          environment: "production"

  - job_name: "Builders Block ASH"
    static_configs:
      # Replace this with the IP address or hostname of your server
      # This will be the service name for Docker Compose users
      - targets: [ "45.59.171.173:25571" ]
        # Customize or/and rewrite your labels (optional)
        labels:
          # The instance label will be shown on the dashboard
          # This is the server's IP address by default
          instance: "buildersblock-ash.trilogymc.net"
          friendly_name: "Builders Block ASH"
          environment: "production"    

  # - job_name: 'example_api'
  #   scheme: http
  #   static_configs:
  #     - targets: ['example_api:9091']

  #  ? TODO: add your services here
  # - job_name: 'your-job-name'
  #   scheme: https
  #   static_configs:
  #     - targets: ['URL_GOES_HERE']
  #   basic_auth:
  #     username: HTTP_AUTH_USERNAME_GOES_HERE
  #     password: HTTP_AUTH_PASSWORD_GOES_HERE
